server:
  port: 8090 #配置程序端口,默认为8080
  session-timeout: 30 #用户会话session过期时间,以秒为单位
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  #context-path: #配置访问路径,默认为/

#查看springboot开启了哪些配置
debug: true

logging:
  level:
    org.springframework.web: DEBUG,CONSOLE
  config: classpath:logback.xml